// frontend/src/App.jsx
import { useState, useEffect } from 'react'
import axios from 'axios'

const API_BASE_URL = 'http://localhost:8000'

function App() {
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [apiStatus, setApiStatus] = useState('checking...')

  useEffect(() => {
    checkApiHealth()
    fetchData()
  }, [])

  const checkApiHealth = async () => {
    try {
      const response = await axios.get(`${API_BASE_URL}/api/health`)
      setApiStatus(`✅ ${response.data.status}`)
    } catch (err) {
      setApiStatus('❌ API not available')
    }
  }

  const fetchData = async () => {
    try {
      setLoading(true)
      const response = await axios.get(`${API_BASE_URL}/api/data`)
      setData(response.data.items)
      setError(null)
    } catch (err) {
      setError('Failed to fetch data from API')
      console.error('Error fetching data:', err)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{
      maxWidth: '800px',
      margin: '0 auto',
      padding: '20px',
      fontFamily: 'Arial, sans-serif'
    }}>
      <header style={{
        textAlign: 'center',
        marginBottom: '40px',
        padding: '20px',
        backgroundColor: 'white',
        borderRadius: '10px',
        boxShadow: '0 2px 10px rgba(0,0,0,0.1)'
      }}>
        <h1 style={{
          color: '#333',
          marginBottom: '10px'
        }}>
          🚀 Barebones App
        </h1>
        <p style={{
          color: '#666',
          margin: '0'
        }}>
          A simple React + FastAPI application
        </p>
        <div style={{
          marginTop: '15px',
          padding: '10px',
          backgroundColor: '#f8f9fa',
          borderRadius: '5px',
          fontSize: '14px'
        }}>
          API Status: <strong>{apiStatus}</strong>
        </div>
      </header>

      <main>
        <section style={{
          backgroundColor: 'white',
          padding: '30px',
          borderRadius: '10px',
          boxShadow: '0 2px 10px rgba(0,0,0,0.1)'
        }}>
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '20px'
          }}>
            <h2 style={{ color: '#333', margin: '0' }}>Data from API</h2>
            <button 
              onClick={fetchData}
              style={{
                backgroundColor: '#007bff',
                color: 'white',
                border: 'none',
                padding: '8px 16px',
                borderRadius: '5px',
                cursor: 'pointer',
                fontSize: '14px'
              }}
            >
              🔄 Refresh
            </button>
          </div>

          {loading && (
            <div style={{
              textAlign: 'center',
              padding: '20px',
              color: '#666'
            }}>
              Loading...
            </div>
          )}

          {error && (
            <div style={{
              backgroundColor: '#f8d7da',
              color: '#721c24',
              padding: '15px',
              borderRadius: '5px',
              marginBottom: '20px'
            }}>
              {error}
            </div>
          )}

          {!loading && !error && (
            <div>
              {data.length > 0 ? (
                <div style={{ display: 'grid', gap: '15px' }}>
                  {data.map(item => (
                    <div key={item.id} style={{
                      border: '1px solid #e0e0e0',
                      borderRadius: '8px',
                      padding: '15px',
                      backgroundColor: '#fafafa'
                    }}>
                      <h3 style={{
                        margin: '0 0 10px 0',
                        color: '#333',
                        fontSize: '18px'
                      }}>
                        {item.name}
                      </h3>
                      <p style={{
                        margin: '0',
                        color: '#666',
                        fontSize: '14px'
                      }}>
                        {item.description}
                      </p>
                    </div>
                  ))}
                </div>
              ) : (
                <div style={{
                  textAlign: 'center',
                  padding: '20px',
                  color: '#666'
                }}>
                  No data available
                </div>
              )}
            </div>
          )}
        </section>
      </main>

      <footer style={{
        textAlign: 'center',
        marginTop: '40px',
        padding: '20px',
        color: '#666',
        fontSize: '14px'
      }}>
        <p>Built with React + Vite + FastAPI</p>
      </footer>
    </div>
  )
}

export default App

// frontend/src/App.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import axios from 'axios'
import { AgGridVue } from 'ag-grid-vue3'
import 'ag-grid-community/styles/ag-grid.css'
import 'ag-grid-community/styles/ag-theme-alpine.css'
import type { ColDef } from 'ag-grid-community'

const API_BASE_URL = 'http://localhost:8000'

interface DataItem {
  id: number
  name: string
  description: string
}

const rowData = ref<DataItem[]>([])
const loading = ref<boolean>(true)
const error = ref<string | null>(null)
const apiStatus = ref<string>('checking...')

// AG Grid column definitions
const columnDefs = ref<ColDef[]>([
  { 
    field: 'olympus_id', 
    headerName: 'ID',
    width: 100,
    sortable: true,
    filter: true
  },
  { 
    field: 'cusip', 
    headerName: 'CUSIP',
    flex: 1,
    sortable: true,
    filter: true
  }
])

// Default grid options
const defaultColDef = ref<ColDef>({
  resizable: true,
  sortable: true,
  filter: true
})

const checkApiHealth = async () => {
  try {
    const response = await axios.get(`${API_BASE_URL}/api/health`)
    apiStatus.value = `✅ ${response.data.status}`
  } catch (err) {
    apiStatus.value = '❌ API not available'
  }
}

const fetchData = async () => {
  try {
    loading.value = true
    const response = await axios.get(`${API_BASE_URL}/api/data`)
    rowData.value = response.data
    error.value = null
  } catch (err) {
    error.value = 'Failed to fetch data from API'
    console.error('Error fetching data:', err)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  checkApiHealth()
  fetchData()
})
</script>

<template>
  <div class="container">
    <header class="header">
      <h1 class="title">🚀 Barebones App</h1>
      <p class="subtitle">A simple Vue.js + FastAPI application</p>
      <div class="status-box">
        API Status: <strong>{{ apiStatus }}</strong>
      </div>
    </header>

    <main>
      <section class="section">
        <div class="section-header">
          <h2 class="section-title">Data from API</h2>
          <button @click="fetchData" class="refresh-button">
            🔄 Refresh
          </button>
        </div>

        <div v-if="loading" class="loading">
          Loading...
        </div>

        <div v-if="error" class="error">
          {{ error }}
        </div>

        <div v-if="!loading && !error" class="grid-container">
          <div v-if="rowData.length > 0">
            <AgGridVue
              class="ag-theme-alpine"
              style="height: 500px; width: 100%;"
              :rowData="rowData"
              :columnDefs="columnDefs"
              :defaultColDef="defaultColDef"
              :pagination="true"
              :paginationPageSize="10"
              :domLayout="'normal'"
            />
          </div>
          <div v-else class="no-data">
            No data available
          </div>
        </div>
      </section>
    </main>

    <footer class="footer">
      <p>Built with Vue.js + Vite + FastAPI</p>
    </footer>
  </div>
</template>

<style scoped>
.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
}

.header {
  text-align: center;
  margin-bottom: 40px;
  padding: 30px;
  background-color: white;
  border-radius: 10px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.title {
  color: #333;
  margin: 0 0 10px 0;
  font-size: 2.5rem;
}

.subtitle {
  color: #666;
  margin: 0;
  font-size: 1.1rem;
}

.status-box {
  margin-top: 15px;
  padding: 10px;
  background-color: #f8f9fa;
  border-radius: 5px;
  font-size: 14px;
}

.section {
  background-color: white;
  padding: 30px;
  border-radius: 10px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 25px;
}

.section-title {
  color: #333;
  margin: 0;
  font-size: 1.5rem;
}

.refresh-button {
  background-color: #007bff;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 5px;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.2s;
}

.refresh-button:hover {
  background-color: #0056b3;
}

.loading,
.no-data {
  text-align: center;
  padding: 40px 20px;
  color: #666;
  font-size: 16px;
}

.error {
  background-color: #f8d7da;
  color: #721c24;
  padding: 15px;
  border-radius: 5px;
  margin-bottom: 20px;
}

.grid-container {
  margin-top: 20px;
}

.ag-theme-alpine {
  --ag-border-radius: 8px;
  --ag-header-background-color: #f8f9fa;
}

.footer {
  text-align: center;
  margin-top: 40px;
  padding: 20px;
  color: #666;
  font-size: 14px;
}

.footer p {
  margin: 0;
}

/* Responsive adjustments */
@media (max-width: 768px) {
  .container {
    padding: 10px;
  }

  .title {
    font-size: 2rem;
  }

  .section-header {
    flex-direction: column;
    gap: 15px;
  }
}
</style>
